-- ============================================
-- Nova Suzuki — Initial Database Schema
-- Oracle Database Migration
-- LGPD Compliant (Lei Nº 13.709/2018)
-- ============================================

--- STATEMENT ---
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE leads';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
--- STATEMENT ---
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE newsletter_subscribers';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
--- STATEMENT ---
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE motorcycles';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
--- STATEMENT ---
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE leads (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR2(255) NOT NULL,
    email             VARCHAR2(255) NOT NULL,
    telefone          VARCHAR2(20) NOT NULL,
    cpf_hash          VARCHAR2(128) NOT NULL,
    cep               VARCHAR2(10) NOT NULL,
    concessionaria    VARCHAR2(255) NOT NULL,
    modelo_interesse  VARCHAR2(500) DEFAULT NULL,
    lgpd_consent      NUMBER(1) DEFAULT 0 NOT NULL,
    lgpd_consent_at   TIMESTAMP NOT NULL,
    ip_masked         VARCHAR2(45) DEFAULT NULL,
    created_at        TIMESTAMP DEFAULT SYSDATE,
    updated_at        TIMESTAMP DEFAULT SYSDATE
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
--- STATEMENT ---
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_leads_email ON leads (email)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 AND SQLCODE != -1408 THEN RAISE; END IF;
END;
--- STATEMENT ---
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_leads_created ON leads (created_at)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 AND SQLCODE != -1408 THEN RAISE; END IF;
END;
--- STATEMENT ---
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE newsletter_subscribers (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR2(255) NOT NULL UNIQUE,
    lgpd_consent      NUMBER(1) DEFAULT 0 NOT NULL,
    lgpd_consent_at   TIMESTAMP NOT NULL,
    is_active         NUMBER(1) DEFAULT 1,
    created_at        TIMESTAMP DEFAULT SYSDATE
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
--- STATEMENT ---
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE motorcycles (
    id                VARCHAR2(50) PRIMARY KEY,
    name              VARCHAR2(255) NOT NULL,
    type              VARCHAR2(20) DEFAULT ''motorcycle'',
    price             NUMBER(12,2) NOT NULL,
    image_url         CLOB NOT NULL,
    description       CLOB DEFAULT NULL,
    features          CLOB DEFAULT NULL,
    is_active         NUMBER(1) DEFAULT 1,
    created_at        TIMESTAMP DEFAULT SYSDATE,
    updated_at        TIMESTAMP DEFAULT SYSDATE
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
--- STATEMENT ---
BEGIN
  INSERT INTO motorcycles (id, name, type, price, image_url, description, features)
  SELECT 'hayabusa', 'Suzuki Hayabusa', 'motorcycle', 124500.00,
         'https://suzukimotos.com.br/storage/images/uploads/modelos/cores/2025-07-11-13-58-59-preta-site.png',
         'O falcão das estradas. Velocidade e elegância em duas rodas.',
         '["Motor 1340cc", "Aerodinâmica Superior", "Tecnologia de Ponta"]'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM motorcycles WHERE id = 'hayabusa');

  INSERT INTO motorcycles (id, name, type, price, image_url, description, features)
  SELECT 'vstrom1050', 'Suzuki V-Strom 1050', 'motorcycle', 74900.00,
         'https://suzukimotos.com.br/storage/images/uploads/modelos/cores/2025-08-05-12-32-40-COR-1.png',
         'A parceira ideal para qualquer aventura, explore novos horizontes sem limites.',
         '["Motor V-Twin 1037cc", "Controle de Tração", "Pilotagem Ride-by-Wire"]'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM motorcycles WHERE id = 'vstrom1050');

  INSERT INTO motorcycles (id, name, type, price, image_url, description, features)
  SELECT 'gsx_s1000', 'Suzuki GSX-S1000', 'motorcycle', 82900.00,
         'https://suzukimotos.com.br/storage/images/uploads/modelos/cores/2025-07-14-12-13-56-azul-site.png',
         'Design agressivo e performance empolgante na categoria naked premium.',
         '["Quick Shift", "Controle de Tração", "Design Agressivo"]'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM motorcycles WHERE id = 'gsx_s1000');

  INSERT INTO motorcycles (id, name, type, price, image_url, description, features)
  SELECT 'gsxr1000', 'Suzuki GSX-R1000R', 'motorcycle', 115000.00,
         'https://suzukimotos.com.br/storage/images/uploads/modelos/cores/2024-06-04-21-14-43-cor.png',
         'A rainha das pistas. Performance pura para quem busca o limite.',
         '["DNA de MotoGP", "Quick Shift", "Controle de Tração"]'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM motorcycles WHERE id = 'gsxr1000');

  INSERT INTO motorcycles (id, name, type, price, image_url, description, features)
  SELECT 'gsx_s1000gx', 'Suzuki GSX-S1000GX', 'motorcycle', 98800.00,
         'https://suzukimotos.com.br/storage/images/uploads/modelos/cores/2025-06-09-14-47-28-azul.png',
         'SUPREME SPORT CROSSOVER',
         '["Suspensão Eletrônica", "Controle de Torque", "Modos de Pilotagem (SDMS)"]'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM motorcycles WHERE id = 'gsx_s1000gx');

  INSERT INTO motorcycles (id, name, type, price, image_url, description, features)
  SELECT 'gsx_s1000gt', 'Suzuki GSX-S1000 GT', 'motorcycle', 92600.00,
         'https://suzukimotos.com.br/storage/images/uploads/modelos/cores/2025-07-25-20-46-31-azul-site.png',
         'A TOURING DO BRASIL. Sinta o prazer da pilotagem Grand Tour.',
         '["Painel TFT 6,5\"", "Conectividade MySpin", "Piloto Automático"]'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM motorcycles WHERE id = 'gsx_s1000gt');

  INSERT INTO motorcycles (id, name, type, price, image_url, description, features)
  SELECT 'gsx_8s', 'Suzuki GSX-8S', 'motorcycle', 51500.00,
         'https://suzukimotos.com.br/storage/images/uploads/modelos/cores/2026-02-25-20-34-13-cor-1.png',
         'POTENCIAL INFINITO. DIVERSÃO ILIMITADA.',
         '["Motor bicilíndrico 776cc", "Quick Shift Bidirecional", "Painel TFT"]'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM motorcycles WHERE id = 'gsx_8s');

  INSERT INTO motorcycles (id, name, type, price, image_url, description, features)
  SELECT 'vstrom_800_de', 'Suzuki V-STROM 800 DE', 'motorcycle', 67500.00,
         'https://suzukimotos.com.br/storage/images/uploads/modelos/cores/2025-11-06-14-43-38-Cor1.png',
         'AVENTURA É O SEU PROPÓSITO.',
         '["Controle de Tração", "Quick Shift", "Suspensão Ajustável"]'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM motorcycles WHERE id = 'vstrom_800_de');

  INSERT INTO motorcycles (id, name, type, price, image_url, description, features)
  SELECT 'gsxr1000r_2024', 'Suzuki GSX-R1000R 2024', 'motorcycle', 109700.00,
         'https://suzukimotos.com.br/storage/images/uploads/modelos/cores/2024-06-04-21-14-43-cor.png',
         'DOMINE AS PISTAS. Uma lenda renovada.',
         '["Controle de Largada", "Quick Shift Bidirecional", "Suspensão Showa"]'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM motorcycles WHERE id = 'gsxr1000r_2024');
  COMMIT;
END;
